version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'urlDB'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:     
    - o-db:/var/lib/mysql
  redis:
    container_name: redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
  o-shortener:
    container_name: o-shortener_container
    build: 
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    links:
      - db
    env_file:
      - ./.env.prod
    command: npm run start:prod
    
volumes:
  o-db:
  cache:
    driver: local