on:
    push: 
        branches: 
            - main 
    workflow_dispatch: 
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: test
              run: echo "welcome"
              shell: bash
    goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: goodbye world
              run: echo "GoodBye World"
              shell: bash

      